CREATE TABLE `USUARIO_TIPO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PAPEL` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(150) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `RG` VARCHAR(30) NOT NULL,
  `SENHA` VARCHAR(30) NOT NULL,
  `ENDERECO` VARCHAR(100) NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `TIPO_USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `RG_UNIQUE` (`RG` ASC),
  INDEX `FK_TIPO_USUARIO_USUARIO` (`TIPO_USUARIO_ID` ASC),
  CONSTRAINT `fk_USUARIO_TIPO_USUARIO1`
    FOREIGN KEY (`TIPO_USUARIO_ID`)
    REFERENCES `USUARIO_TIPO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `VENDA_STATUS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `VENDA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `VALOR_SUBTOTAL` DECIMAL NOT NULL,
  `VALOR_TOTAL` DECIMAL NOT NULL,
  `DATA` DATE NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  `VENDA_STATUS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_USUARIO_VENDA` (`USUARIO_ID` ASC),
  INDEX `FK_VENDA_STATUS_VENDA` (`VENDA_STATUS_ID` ASC),
  CONSTRAINT `fk_VENDA_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDA_VENDA_STATUS1`
    FOREIGN KEY (`VENDA_STATUS_ID`)
    REFERENCES `VENDA_STATUS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `VENDA_PRODUTO` (
  `VENDA_ID` INT NOT NULL,
  `PRODUTO_ID` INT NOT NULL,
  `VALOR_UNITARIO` DECIMAL NOT NULL,
  `VALOR_SUBTOTAL` DECIMAL NOT NULL,
  `VALOR_TOTAL` DECIMAL NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  PRIMARY KEY (`VENDA_ID`, `PRODUTO_ID`),
  INDEX `FK_PRODUTO_VENDA_PRODUTO` (`PRODUTO_ID` ASC),
  INDEX `FK_VENDA_VENDA_PRODUTO` (`VENDA_ID` ASC),
  CONSTRAINT `fk_VENDA_has_PRODUTO_VENDA2`
    FOREIGN KEY (`VENDA_ID`)
    REFERENCES `VENDA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDA_has_PRODUTO_PRODUTO2`
    FOREIGN KEY (`PRODUTO_ID`)
    REFERENCES `PRODUTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `RESERVA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_INICIAL` DATE NOT NULL,
  `DATA_FINAL` DATE NOT NULL,
  `VENDA_ID` INT NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_VENDA_RESERVA` (`VENDA_ID` ASC),
  INDEX `FK_USUARIO_RESERVA` (`USUARIO_ID` ASC),
  CONSTRAINT `fk_RESERVA_VENDA1`
    FOREIGN KEY (`VENDA_ID`)
    REFERENCES `VENDA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USUARIO_TIPO (PAPEL) VALUES
("Admin"), 
("Cliente"); 

INSERT INTO VENDA_STATUS (NOME) VALUES
("Finalizada"), 
("Cancelada"), 
("Reservada"); 

